import './globals.css'
import type { Metadata } from 'next'
import { Titillium_Web } from 'next/font/google'

const titillium_Web = Titillium_Web({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={titillium_Web.className}>{children}</body>
    </html>
  )
}
